// Code generated by MockGen. DO NOT EDIT.
// Source: otp_repository.go
//
// Generated by this command:
//
//	mockgen -source=otp_repository.go -destination=mock/otp_repository_mock.go -package=mock_repository
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	model "furab-backend/services/otp-service/internal/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockOTPRepository is a mock of OTPRepository interface.
type MockOTPRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOTPRepositoryMockRecorder
	isgomock struct{}
}

// MockOTPRepositoryMockRecorder is the mock recorder for MockOTPRepository.
type MockOTPRepositoryMockRecorder struct {
	mock *MockOTPRepository
}

// NewMockOTPRepository creates a new mock instance.
func NewMockOTPRepository(ctrl *gomock.Controller) *MockOTPRepository {
	mock := &MockOTPRepository{ctrl: ctrl}
	mock.recorder = &MockOTPRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOTPRepository) EXPECT() *MockOTPRepositoryMockRecorder {
	return m.recorder
}

// FindByPhone mocks base method.
func (m *MockOTPRepository) FindByPhone(ctx context.Context, phone string) (*model.OTP, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByPhone", ctx, phone)
	ret0, _ := ret[0].(*model.OTP)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByPhone indicates an expected call of FindByPhone.
func (mr *MockOTPRepositoryMockRecorder) FindByPhone(ctx, phone any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByPhone", reflect.TypeOf((*MockOTPRepository)(nil).FindByPhone), ctx, phone)
}

// ResendOTP mocks base method.
func (m *MockOTPRepository) ResendOTP(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResendOTP", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResendOTP indicates an expected call of ResendOTP.
func (mr *MockOTPRepositoryMockRecorder) ResendOTP(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResendOTP", reflect.TypeOf((*MockOTPRepository)(nil).ResendOTP), ctx)
}

// Save mocks base method.
func (m *MockOTPRepository) Save(ctx context.Context, otp *model.OTP) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, otp)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockOTPRepositoryMockRecorder) Save(ctx, otp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockOTPRepository)(nil).Save), ctx, otp)
}

// SendOTP mocks base method.
func (m *MockOTPRepository) SendOTP(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendOTP", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendOTP indicates an expected call of SendOTP.
func (mr *MockOTPRepositoryMockRecorder) SendOTP(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendOTP", reflect.TypeOf((*MockOTPRepository)(nil).SendOTP), ctx)
}

// VerifyOTP mocks base method.
func (m *MockOTPRepository) VerifyOTP(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyOTP", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// VerifyOTP indicates an expected call of VerifyOTP.
func (mr *MockOTPRepositoryMockRecorder) VerifyOTP(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyOTP", reflect.TypeOf((*MockOTPRepository)(nil).VerifyOTP), ctx)
}
